###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
        image: mysql:5.7
        container_name: books-manager-mysql
        working_dir: /application
        volumes:
            - .:/application
            - data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=book-manager
            - MYSQL_USER=symfony
            - MYSQL_PASSWORD=symfony
        ports:
            - "8082:3306"

    webserver:
        image: nginx:alpine
        container_name: books-manager-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    php-fpm:
        build: docker/php-fpm
        container_name: books-manager-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        links:
            - mysql:mysql

volumes:
    data:
